### ISSUE TITLE
Doesn't work on Linux yet

### ISSUE THREAD

**Issue by rkakrik** [fyne-io/systray#2]
Traceback:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x8c5b8d]

goroutine 15 [running]:
github.com/godbus/dbus/v5.(*Conn).getSerial(...)
	/home/krik/go/pkg/mod/github.com/godbus/dbus/v5@v5.1.0/conn.go:369
github.com/godbus/dbus/v5.(*Conn).sendMessageAndIfClosed(0x0, 0xc000520810, 0xc000520870?)
	/home/krik/go/pkg/mod/github.com/godbus/dbus/v5@v5.1.0/conn.go:490 +0x2d
github.com/godbus/dbus/v5.(*Conn).Emit(0xc0005207e0?, {0xad5c4d, 0x13}, {0xc00040e3c0, 0x24}, {0xc0000781e0?, 0x2, 0x2})
	/home/krik/go/pkg/mod/github.com/godbus/dbus/v5@v5.1.0/export.go:245 +0x4d0
fyne.io/systray/internal/generated/menu.Emit(0xc00031a140?, {0xbeb0f0, 0xc0005207e0})
	/home/krik/go/pkg/mod/fyne.io/systray@v1.9.0/internal/generated/menu/dbus_menu.go:88 +0x111
fyne.io/systray.refresh(...)
	/home/krik/go/pkg/mod/fyne.io/systray@v1.9.0/systray_menu_linux.go:203
fyne.io/systray.addOrUpdateMenuItem(0xc00031a140)
	/home/krik/go/pkg/mod/fyne.io/systray@v1.9.0/systray_menu_linux.go:131 +0x35b
fyne.io/systray.(*MenuItem).update(0xc00031a140)
	/home/krik/go/pkg/mod/fyne.io/systray@v1.9.0/systray.go:224 +0x7e
fyne.io/systray.(*MenuItem).Disable(...)
	/home/krik/go/pkg/mod/fyne.io/systray@v1.9.0/systray.go:189
main.onReady()
	/home/krik/wrk/traceiq/esf/esf.go:109 +0x92
fyne.io/systray.Register.func2()
	/home/krik/go/pkg/mod/fyne.io/systray@v1.9.0/systray.go:98 +0x32
created by fyne.io/systray.Register
	/home/krik/go/pkg/mod/fyne.io/systray@v1.9.0/systray.go:96 +0xc5
```

**Comment by rkakrik** [comment]
/home/krik/wrk/traceiq/esf/esf.go:109:
```go
systray.AddMenuItem("connected", "Status").Disable()
```

**Comment by andydotxyz** [comment]
Can you please provide some information about your Linux system, and desktop setup?
It does work on many Linux setups, so something different is happening in your configuration and we will need help understanding what.

**Comment by rkakrik** [comment]
Distro: Archlinux
* gtk4 1:4.6.2-1
* gtk3 1:3.24.33-2
* libappindicator-gtk3 12.10.0.r296-1
* dbus 1.14.0-1

**Comment by rkakrik** [comment]
Same build for windows works fine in wine

**Comment by andydotxyz** [comment]
It would be good to know if version `d5779bf` still shows the same problem

**Comment by andydotxyz** [comment]
Ah, apologies there was a missing nil check, version `9177bf8` fixes it
