### ISSUE TITLE
Panic in disabling MenuItem

### ISSUE THREAD

**Issue by mrpalide** [fyne-io/systray#7]
I want switch from getlantern to your fork because of cgo free, but I get this panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0xa35ced]

goroutine 8 [running]:
github.com/godbus/dbus/v5.(*Conn).getSerial(...)
	/home/ubuntu/me_skywire/vendor/github.com/godbus/dbus/v5/conn.go:354
github.com/godbus/dbus/v5.(*Conn).sendMessageAndIfClosed(0x0, 0xc0001cd6b0, 0xbcf6cc)
	/home/ubuntu/me_skywire/vendor/github.com/godbus/dbus/v5/conn.go:475 +0x2d
github.com/godbus/dbus/v5.(*Conn).Emit(0xc0001cd650, {0xbdd1ce, 0x13}, {0xc00019a510, 0x7f1cef789bc0}, {0xc000069680, 0x2, 0x2})
	/home/ubuntu/me_skywire/vendor/github.com/godbus/dbus/v5/export.go:223 +0x4dd
fyne.io/systray/internal/generated/menu.Emit(0xc000162f80, {0x12b6e58, 0xc0001cd650})
	/home/ubuntu/me_skywire/vendor/fyne.io/systray/internal/generated/menu/dbus_menu.go:88 +0x111
fyne.io/systray.refresh(...)
	/home/ubuntu/me_skywire/vendor/fyne.io/systray/systray_menu_linux.go:203
fyne.io/systray.addOrUpdateMenuItem(0xc000162f80)
	/home/ubuntu/me_skywire/vendor/fyne.io/systray/systray_menu_linux.go:131 +0x35b
fyne.io/systray.(*MenuItem).update(0xc000162f80)
	/home/ubuntu/me_skywire/vendor/fyne.io/systray/systray.go:224 +0x7e
fyne.io/systray.(*MenuItem).Disable(...)

```
when trying to run this part of code:
```
mLink = systray.AddMenuItem("Open UI", "Open UI in browser")
mLink.Disable()
```

Actually it works fine on getlantern. :(

**Comment by mrpalide** [comment]
I was in WRONG commit :|
